### PR TITLE
Await RequestObserver tasks

### PR DESCRIPTION
**Pull request by joao-r-reis**

### CODE REVIEW

**Comment by joao-r-reis** [comment]
Hmm I'm seeing quite a performance degradation with these async changes. Let me run a couple more benchmarks tomorrow, if this is confirmed then I might close this PR and open a new one from the other branch I have with changes to make the request tracker methods synchronous.

**Comment by joao-r-reis** [comment]
Actually I'll close the PR for now

**Comment by joao-r-reis** [comment]
I've changed the composite classes to avoid collections since we always use 2 (metrics and request tracker). In the future if we need to support multiple request trackers then we can change these classes to support collections again but for now this allows us to mitigate the performance impact of these changes (decrease in allocations)

**Comment by simaoribeiro** [comment]
Can I merge this @joao-r-reis ?

**Comment by joao-r-reis** [comment]
Yes

**Pull request merged**
